---
# install Apache2 using Ansible
- name: Setup Apache server on myservers
  hosts: EC2webserver
  become: True
  vars:
    apache2_version: 2.4.41
  tasks:
    # first task --- instal apache2
    - name: Install the latest version of apache2
      command: sudo apt install apache2 apache2-utils -y

    
    #second task --- start the service
    - name: Start apache2
      service:
        name: apache2
        enabled: yes
        state: started

    # third task --- confirm apache2 version
    - name: Get apache2 installed version
      command: apache2 -v
      register: apache2_version
    # print the current version of apache2 on screen
    - name: print apache2 version
      debug:
        msg: "The current version of apache2 is {{apache2_version}}"

    # forth task --- confirm status
    - name: Get the status of apache2 service
      command: systemctl status apache2

    # fifth task --- set server to Africa/Lagos timezone
    - name: Set timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos

    # sixth task --- confirm time zone has been changed correctly
    - name: Get status of timezone
      command: timedatectl

    #Install php8.1
    - name: Installation install software-properties-common
      apt: name=software-properties-common

    - name: "Repo PHP 7.4"
      apt_repository:
        repo="ppa:ondrej/php"

    - name: "Updating the repo"
      apt: update_cache=yes

    - name: Installation PHP 7.4
      apt: name=php7.4 state=present

    - name: install lamp stack
      apt:
        pkg:
          - php7.4-mysql
          - php7.4-curl
          - php7.4-json
          - php7.4-cgi
          - php7.4-xsl
          - php7.4-cgi
          - php7.4-gd
          - php7.4-mbstring
          - php7.4-zip
          - php7.4-xmlrpc
          - php7.4-soap
          - php7.4-intl
          - libapache2-mod-php
        state: present
        update_cache: yes

    #Copy index.php file apache web hosting path
    - name: copy file from localhost(this VM) to remote server
      copy:
        src: /home/vagrant/ansible/index.php
        dest: /var/www/html/index.php
